const voyagesData = [
  {
    IdVoyage: 1,
    Nom: "L'essentiel du Grand-Popo",
    Description: "Une évasion de trois jours le long de la côte atlantique. Ce voyage met en lumière le charme paisible de **Grand-Popo** avec ses plages de sable fin, et culmine par une balade en pirogue vers la **Bouche du Roy**, l'endroit spectaculaire où le fleuve Mono rencontre l'océan, un écosystème unique et préservé.",
    Avis: "4.8/5 (120)",
    Prix: 125000,
    NombresDeVoyageurs: 2,
    Destinations: "Grand-Popo, Bouche du Roy",
    DateDeDepart: "2026-03-15",
    GaleriesDImages: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBOGTbgt8IXH9hNK6xWrBfbaZO1mXXVJ01UbKpBNOr-BrNA6XdrhCOJuCW7QUTnCPyLNmOY51jJZmpNQifDVmY9cp6YT0P6cswftHoncLhr2Z9A2X_IgJxUBzmkpd4WVDWobqYTT1MpGPTttcI47rFMYjzr4oAPTNyudGhNCcpxHvmXbd_baqE1xfSdN3QV8Osb6B9IlIVSJadRRB8DJHgATpFFObwi4bt-uiDoGHCLx1DB52AgpLl68w_akT0Bo_6LP2p_fO5sDPIZ",
      "https://www.shutterstock.com/fr/search/grand-popo",
      "https://www.tripadvisor.fr/Attraction_Review-g1940386-d13146435-Reviews-La_Bouche_Du_Roy-Grand_Popo_Mono_Department.html",
      "https://www.booking.com/hotel/bj/awale-plage.fr.html",
      "https://www.shutterstock.com/fr/search/benin-plage"
    ],
    Inclusions: "Hébergement 3*, transport A/R Cotonou, 2 dîners.",
  },
  {
    IdVoyage: 2,
    Nom: "Randonnée mystique Koutammakou",
    Description: "Un trek immersif de 3 jours dans le **Pays des Somba** (Koutammakou), un site classé au patrimoine mondial de l'UNESCO. Vous explorerez les 'Tata Somba', ces étonnantes constructions en terre fortifiées, et partagerez le quotidien des habitants pour comprendre leurs traditions ancestrales et leurs croyances mystiques.",
    Avis: "4.9/5 (55)",
    Prix: 280000,
    NombresDeVoyageurs: 4,
    Destinations: "Koutammakou, Natitingou",
    DateDeDepart: "2026-05-01",
    GaleriesDImages: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBCx05VVKi5nvpe2hpoVySoW9XZmvlDm3CzBqdrdNCPp7tVo2buOnY_56jIb7dnUqNmc0G1e74azsu3j8CsQb4yl6Cg18poxUX7igwEcubC6Xf3VdaVGujsfNfqqdTtgr4SqDKFygK5gxUAompWxZk6cHHNlouXALVOcZ4CUMroBnfwrVfKnQ36zQlhskUCD6Zko5go8GQBhBiWDh2PnK1RvRI74ASzu7rDSGzn2-RQFqyBiby8R7xRc7qb6MYnhoBmIk-uPQRkDNWb",
      "https://whc.unesco.org/fr/list/1140",
      "https://www.gettyimages.fr/photos/tata-somba",
      "https://www.youtube.com/watch?v=wz3i9YQ8Z-g",
      "https://www.istockphoto.com/fr/search/2/image?phrase=tata+somba"
    ],
    Inclusions: "Guide local, nuit chez l'habitant, 3 repas/jour, droits d'entrée.",
  },
  {
    IdVoyage: 3,
    Nom: "Circuit historique Abomey",
    Description: "Plongez au cœur de l'histoire du puissant royaume du Dahomey (1600-1900). Ce circuit d'une journée entière vous guide à travers les **Palais Royaux d'Abomey** (patrimoine UNESCO), révélant les secrets des douze rois qui y régnèrent, leurs rites et leur art. Une étape indispensable pour les passionnés d'histoire africaine.",
    Avis: "4.6/5 (89)",
    Prix: 45000,
    NombresDeVoyageurs: 1,
    Destinations: "Abomey, Bohicon",
    DateDeDepart: "2026-04-10",
    GaleriesDImages: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBjN3j_fVFmUnX_tNXg8dVno4IuCwKEApWvdHNI9EGSH-iMSnBNWsLZSsEdCnU-4WbKhz6X0Z0kXAfKOtXhT5f0UA_xVFwsEenOgWvavKuAKBmSDCMhvlFCyIDHPVKY7vNws56_wO2cugmHHyFdvPvetiYk9F25dsXtgHgW49DdrO13Owl4Bu8an1VEsbF_IOTR-v8tt8ewUgKD4SkA38JQPqUpMObXmdTDBR4Czmenfpcd4PXvftV5lj9-q5doSDPwuAslmltM7nwn",
      "https://geoconfluences.ens-lyon.fr/informations-scientifiques/a-la-une/image-a-la-une/ouidah",
      "https://whc.unesco.org/fr/list/323",
      "https://www.shutterstock.com/fr/search/palais+royaux+abomey",
      "https://www.istockphoto.com/fr/search/2/image?phrase=palais+royaux+abomey"
    ],
    Inclusions: "Transport local Abomey, entrée aux palais, guide historien.",
  },
  {
    IdVoyage: 4,
    Nom: "Week-end détente Cotonou",
    Description: "Deux jours dédiés à la relaxation et au confort dans la capitale économique. Profitez d'un séjour en **hôtel 4 étoiles à Fidjrossè**, avec accès à une plage privée immaculée et une piscine. Le forfait inclut un petit-déjeuner gourmand et est parfait pour s'échapper du tumulte de la semaine.",
    Avis: "4.7/5 (72)",
    Prix: 90000,
    NombresDeVoyageurs: 3,
    Destinations: "Cotonou, Fidjrossè",
    DateDeDepart: "2026-02-28",
    GaleriesDImages: [
      "https://www.photo-alsace.com/photo-ref-n40829.html",
      "https://www.shutterstock.com/fr/search/benin-outdoor",
      "https://www.tripadvisor.fr/Attractions-g297920-Activities-c61-t52-Cotonou_Littoral_Department.html",
      "https://www.booking.com/city/bj/cotonou.fr.html",
      "https://www.gettyimages.fr/photos/cotonou-plage"
    ],
    Inclusions: "Nuit en suite, petit-déjeuner buffet, accès spa.",
  },
  {
    IdVoyage: 5,
    Nom: "Safari Parc Pendjari",
    Description: "Une aventure de 4 jours et 3 nuits au cœur de l'Afrique de l'Ouest. Le **Parc National de la Pendjari** est réputé pour sa concentration de grands mammifères : éléphants, lions, buffles, et antilopes. L'expérience se fait en 4x4 privé avec un guide tracker expérimenté, garantissant des rencontres inoubliables avec la faune.",
    Avis: "5.0/5 (32)",
    Prix: 550000,
    NombresDeVoyageurs: 2,
    Destinations: "Parc National de la Pendjari",
    DateDeDepart: "2026-11-05",
    GaleriesDImages: [
      "https://www.youtube.com/watch?v=Ez1ozpEkkrg",
      "https://www.shutterstock.com/fr/search/benin-outdoor",
      "https://www.parc-pendjari.net/en/explore/photo-gallery/",
      "https://www.gettyimages.fr/photos/parc-national-de-la-pendjari",
      "https://www.istockphoto.com/fr/search/2/image?phrase=parc+national+de+la+pendjari"
    ],
    Inclusions: "4x4 privé, guide tracker, hébergement en lodge, pension complète.",
  },
  {
    IdVoyage: 6,
    Nom: "Aventure Ganvié, la Venise de l'Afrique",
    Description: "Découvrez **Ganvié**, la plus grande cité lacustre d'Afrique, où tout se passe sur l'eau. Embarquez pour une excursion d'une journée sur le **Lac Nokoué** pour observer le mode de vie fascinant des Toffins, leurs marchés flottants, leurs habitations sur pilotis, et partagez un déjeuner traditionnel directement sur l'eau.",
    Avis: "4.5/5 (150)",
    Prix: 25000,
    NombresDeVoyageurs: 5,
    Destinations: "Ganvié, Lac Nokoué",
    DateDeDepart: "2026-03-20",
    GaleriesDImages: [
      "https://www.shutterstock.com/fr/search/ganvie",
      "https://whc.unesco.org/fr/list/158/",
      "https://www.gettyimages.fr/photos/ganvi%C3%A9",
      "https://www.youtube.com/watch?v=kY3j9o4gV4M",
      "https://www.istockphoto.com/fr/search/2/image?phrase=ganvie"
    ],
    Inclusions: "Transport A/R Calavi, pirogue privée, déjeuner flottant.",
  },
  {
    IdVoyage: 7,
    Nom: "Route des esclaves Ouidah",
    Description: "Un voyage émouvant à **Ouidah**, point névralgique de la traite négrière. La visite retrace le chemin parcouru par les esclaves, du **Temple des Pythons** au Fort Portugais, jusqu'à l'océan, à la fameuse **Porte du Non-Retour**. Ce circuit est un devoir de mémoire essentiel pour comprendre l'histoire de la région.",
    Avis: "4.7/5 (112)",
    Prix: 30000,
    NombresDeVoyageurs: 1,
    Destinations: "Ouidah",
    DateDeDepart: "2026-06-01",
    GaleriesDImages: [
      "https://journals.openedition.org/slaveries/4305",
      "https://geoconfluences.ens-lyon.fr/informations-scientifiques/a-la-une/image-a-la-une/ouidah",
      "https://www.youtube.com/watch?v=T_8N_nJ5w7g",
      "https://www.shutterstock.com/fr/search/route+des+esclaves+ouidah",
      "https://www.gettyimages.fr/photos/porte-du-non-retour"
    ],
    Inclusions: "Guide local (Français/Anglais), transport sur place (moto-taxi).",
  },
  {
    IdVoyage: 8,
    Nom: "Immersion cuisine béninoise",
    Description: "Un atelier culinaire d'une demi-journée à **Porto-Novo**. Sous la guidance d'un chef local, vous commencerez par la sélection des produits frais au marché, puis apprendrez à préparer des mets typiques comme la pâte (igname, maïs) et les sauces traditionnelles (arachide, tomate). L'atelier se termine par la dégustation de vos créations.",
    Avis: "4.8/5 (40)",
    Prix: 50000,
    NombresDeVoyageurs: 2,
    Destinations: "Porto-Novo",
    DateDeDepart: "2026-07-14",
    GaleriesDImages: [
      "https://www.shutterstock.com/fr/search/porto-novo-b%C3%A9nin",
      "https://www.youtube.com/watch?v=B7bX1o5h8fU",
      "https://www.gettyimages.fr/photos/cuisine-b%C3%A9ninoise",
      "https://www.istockphoto.com/fr/search/2/image?phrase=march%C3%A9+porto-novo",
      "https://www.tripadvisor.fr/Attractions-g1205628-Activities-c36-t192-Porto_Novo_Oueme_Department.html"
    ],
    Inclusions: "Cours de cuisine, ingrédients, dégustation et recettes.",
  },
  {
    IdVoyage: 9,
    Nom: "Fête du Non-Retour (Période)",
    Description: "Un package exclusif pour vivre l'atmosphère électrisante de la Fête du Non-Retour ou d'autres événements culturels majeurs en janvier. Ce séjour inclut l'accès privilégié aux **cérémonies vaudou** et aux spectacles traditionnels à **Ouidah**, offrant une perspective unique sur la spiritualité béninoise.",
    Avis: "4.9/5 (18)",
    Prix: 180000,
    NombresDeVoyageurs: 3,
    Destinations: "Ouidah, Cotonou",
    DateDeDepart: "2026-01-10",
    GaleriesDImages: [
      "https://fr.wikipedia.org/wiki/Vodun_Days",
      "https://geoconfluences.ens-lyon.fr/informations-scientifiques/a-la-une/image-a-la-une/ouidah",
      "https://www.shutterstock.com/fr/search/f%C3%AAte+vaudou+ouidah",
      "https://www.gettyimages.fr/photos/voodoo-day-benin",
      "https://www.youtube.com/watch?v=F3S0w0B0D_o"
    ],
    Inclusions: "Billets événements, transport VIP, hébergement 3 nuits.",
  },
  {
    IdVoyage: 10,
    Nom: "Escapade montagnarde Dassa-Zoumè",
    Description: "Une journée de randonnée rafraîchissante à **Dassa-Zoumè**, connue comme la 'Ville des 41 collines'. Cette excursion spirituelle vous emmènera au sommet de plusieurs collines sacrées, offrant des vues panoramiques spectaculaires sur la brousse environnante. Idéal pour les amoureux de la nature et de la marche.",
    Avis: "4.6/5 (68)",
    Prix: 70000,
    NombresDeVoyageurs: 4,
    Destinations: "Dassa-Zoumè",
    DateDeDepart: "2026-08-22",
    GaleriesDImages: [
      "https://www.hemis.fr/image-photo/3600040/benin-dassa-zoume-sommet-collines-dassa-presentant-trous-vestiges-habitants-fuyant-negriers-vivaient.html",
      "https://www.shutterstock.com/fr/search/benin-outdoor",
      "https://www.youtube.com/watch?v=L2Gj9g0gS3c",
      "https://www.gettyimages.fr/photos/dassa-zoum%C3%A8",
      "https://www.tripadvisor.fr/Attractions-g1466085-Activities-Dassa_Zoume_Collines_Department.html"
    ],
    Inclusions: "Guide de randonnée, pique-nique local, transport A/R.",
  },
  {
    IdVoyage: 11,
    Nom: "Circuit Eco-Tourisme Pêche",
    Description: "Un séjour axé sur la durabilité et l'immersion. Vous passerez trois jours au bord du **Lac Ahémé** ou dans le village de **Togbin**, vivant au rythme des communautés de pêcheurs. Vous participerez aux techniques de pêche traditionnelles, apprendrez sur l'écologie locale et serez logé simplement chez l'habitant.",
    Avis: "4.7/5 (25)",
    Prix: 160000,
    NombresDeVoyageurs: 2,
    Destinations: "Togbin, Lac Ahémé",
    DateDeDepart: "2026-09-03",
    GaleriesDImages: [
      "https://www.youtube.com/watch?v=yQIKEk9oPLA",
      "https://www.shutterstock.com/fr/search/fishing-benin",
      "https://www.tripadvisor.fr/Attraction_Review-g1940386-d12822557-Reviews-Lac_Aheme-Grand_Popo_Mono_Department.html",
      "https://www.gettyimages.fr/photos/lac-aheme",
      "https://www.istockphoto.com/fr/search/2/image?phrase=p%C3%AAcheurs+benin"
    ],
    Inclusions: "Participation aux activités de pêche, hébergement simple, pension complète.",
  },
  {
    IdVoyage: 12,
    Nom: "Bénin Express (5 jours)",
    Description: "Le circuit idéal pour découvrir les incontournables du sud du Bénin en moins d'une semaine. Ce voyage optimisé vous fait passer par **Cotonou** (marchés, artisanat), **Ouidah** (histoire), et **Ganvié** (village lacustre). Tous les transports sont inclus, assurant une transition fluide entre les sites historiques et culturels majeurs.",
    Avis: "4.5/5 (95)",
    Prix: 320000,
    NombresDeVoyageurs: 3,
    Destinations: "Cotonou, Ouidah, Ganvié",
    DateDeDepart: "2026-04-05",
    GaleriesDImages: [
      "https://www.shutterstock.com/fr/search/ganvie",
      "https://journals.openedition.org/slaveries/4305",
      "https://www.photo-alsace.com/photo-ref-n40829.html",
      "https://www.youtube.com/watch?v=yQIKEk9oPLA",
      "https://www.gettyimages.fr/photos/benin-voyage"
    ],
    Inclusions: "Tous transports inter-villes, hôtels 3*, guide accompagnateur.",
  },
  {
    IdVoyage: 13,
    Nom: "Exploration des grottes de Savalou",
    Description: "Voyage d'une journée à **Savalou** pour explorer ses grottes sacrées. Ces cavités sont des lieux de pèlerinage importants pour les adeptes du Vaudou et de l'Animisme. La visite, guidée par un local, permet de comprendre l'importance spirituelle et l'histoire géologique de ces sanctuaires naturels.",
    Avis: "4.4/5 (42)",
    Prix: 55000,
    NombresDeVoyageurs: 1,
    Destinations: "Savalou",
    DateDeDepart: "2026-10-18",
    GaleriesDImages: [
      "https://www.gettyimages.fr/photos/savalou",
      "https://www.youtube.com/watch?v=F3S0w0B0D_o",
      "https://www.shutterstock.com/fr/search/savalou",
      "https://www.tripadvisor.fr/Attraction_Review-g1940386-d13146435-Reviews-La_Bouche_Du_Roy-Grand_Popo_Mono_Department.html",
      "https://www.istockphoto.com/fr/search/2/image?phrase=grotte+savalou"
    ],
    Inclusions: "Transport depuis Dassa, guide local, lampe torche.",
  },
  {
    IdVoyage: 14,
    Nom: "VTT dans la région des Collines",
    Description: "Un circuit sportif de 2 jours pour les aventuriers. Parcourez la **région des Collines** en Vélo Tout Terrain (VTT), traversant des paysages pittoresques et des villages reculés. Le voyage inclut une nuit en **campement à la belle étoile** et des repas rustiques pour une expérience 100% nature.",
    Avis: "4.9/5 (15)",
    Prix: 110000,
    NombresDeVoyageurs: 5,
    Destinations: "Savalou, Collines",
    DateDeDepart: "2026-11-25",
    GaleriesDImages: [
      "https://www.shutterstock.com/fr/search/benin-outdoor",
      "https://www.hemis.fr/image-photo/3600040/benin-dassa-zoume-sommet-collines-dassa-presentant-trous-vestiges-habitants-fuyant-negriers-vivaient.html",
      "https://www.gettyimages.fr/photos/collines-benin",
      "https://www.istockphoto.com/fr/search/2/image?phrase=vtt+afrique",
      "https://www.youtube.com/watch?v=L2Gj9g0gS3c"
    ],
    Inclusions: "Location VTT, équipement de camping, repas de brousse.",
  },
  {
    IdVoyage: 15,
    Nom: "Réveillon à la plage",
    Description: "Célébrez le Nouvel An d'une manière mémorable à **Possotomè**. Ce forfait offre un dîner de gala raffiné servi directement sur la plage, suivi d'un spectacle de feux d'artifice au-dessus de l'océan. Le séjour inclut une nuit dans un bungalow en bord de mer pour une transition douce vers la nouvelle année.",
    Avis: "4.8/5 (30)",
    Prix: 195000,
    NombresDeVoyageurs: 2,
    Destinations: "Possotomè, Plage",
    DateDeDepart: "2026-12-31",
    GaleriesDImages: [
      "https://www.shutterstock.com/fr/search/grand-popo",
      "https://www.hotel-benin-awaleplage.com/noel-nouvel-an-sous-les-cocotiers/",
      "https://www.youtube.com/watch?v=L2Gj9g0gS3c",
      "https://www.tripadvisor.fr/Attraction_Review-g1940386-d13146435-Reviews-La_Bouche_Du_Roy-Grand_Popo_Mono_Department.html",
      "https://www.gettyimages.fr/photos/plage-grand-popo"
    ],
    Inclusions: "Dîner de gala, feux d'artifice, hébergement une nuit en bungalow.",
  },
  {
    IdVoyage: 16,
    Nom: "Voyage spirituel (Vaudou)",
    Description: "Un tour hautement spécialisé pour ceux qui souhaitent une immersion profonde dans le **Vaudou béninois**. Ce circuit de 3 jours vous emmène sur des sites de culte clés à **Ouidah**, **Abomey**, et **Allada**, et peut inclure, selon la période, l'accès à des **cérémonies traditionnelles privées** avec l'aide d'un guide initié.",
    Avis: "4.7/5 (20)",
    Prix: 250000,
    NombresDeVoyageurs: 3,
    Destinations: "Ouidah, Abomey, Allada",
    DateDeDepart: "2026-01-20",
    GaleriesDImages: [
      "https://geoconfluences.ens-lyon.fr/informations-scientifiques/a-la-une/image-a-la-une/ouidah",
      "https://fr.wikipedia.org/wiki/Vodun_Days",
      "https://www.shutterstock.com/fr/search/c%C3%A9r%C3%A9monie+vaudou+benin",
      "https://www.gettyimages.fr/photos/voodoo-day-benin",
      "https://www.youtube.com/watch?v=F3S0w0B0D_o"
    ],
    Inclusions: "Accès à des cérémonies privées, guide initié, transport.",
  },
  {
    IdVoyage: 17,
    Nom: "La Casse de Pêche de Cotonou",
    Description: "Une matinée éducative et vibrante sur la **plage de pêche de Cotonou**. Vous assisterez au retour des pêcheurs, à la négociation du poisson, et aux techniques de fumage. Le circuit se termine par une **dégustation** de poisson frais grillé sur place, offrant un aperçu authentique de l'activité maritime béninoise.",
    Avis: "4.3/5 (78)",
    Prix: 15000,
    NombresDeVoyageurs: 1,
    Destinations: "Cotonou, Plage de pêche",
    DateDeDepart: "2026-02-05",
    GaleriesDImages: [
      "https://www.shutterstock.com/fr/search/fishing-benin",
      "https://www.youtube.com/watch?v=yQIKEk9oPLA",
      "https://www.gettyimages.fr/photos/march%C3%A9-poisson-cotonou",
      "https://www.istockphoto.com/fr/search/2/image?phrase=casse+de+p%C3%AAche+cotonou",
      "https://www.photo-alsace.com/photo-ref-n40829.html"
    ],
    Inclusions: "Guide local, dégustation de poisson grillé.",
  },
  {
    IdVoyage: 18,
    Nom: "Détente à l'hôtel Elmina",
    Description: "Un séjour de luxe de 3 jours et 2 nuits dans un établissement haut de gamme à **Grand-Popo**. L'offre inclut une **suite avec vue sur mer**, une demi-pension gastronomique et un massage offert au spa de l'hôtel. C'est l'escapade parfaite pour se ressourcer avec un service irréprochable et un cadre idyllique en bord de mer.",
    Avis: "4.9/5 (48)",
    Prix: 380000,
    NombresDeVoyageurs: 2,
    Destinations: "Grand-Popo",
    DateDeDepart: "2026-05-15",
    GaleriesDImages: [
      "https://www.shutterstock.com/fr/search/grand-popo",
      "https://www.hotel-benin-awaleplage.com/noel-nouvel-an-sous-les-cocotiers/",
      "https://fr.trip.com/hotels/grand-popo-1-hotel-detail-22061892/millnium-popo-beach-hotel/",
      "https://www.booking.com/hotel/bj/awale-plage.fr.html",
      "https://www.gettyimages.fr/photos/grand-popo+h%C3%B4tel"
    ],
    Inclusions: "Suite vue mer, demi-pension gastronomique, massage offert.",
  },
  {
    IdVoyage: 19,
    Nom: "Circuit Artisanal Bénin",
    Description: "Une journée dédiée à la découverte du riche artisanat béninois. Visitez des centres de production à **Abomey-Calavi** et **Sékou** pour observer les maîtres potiers, sculpteurs sur bois, et tisserands à l'œuvre. C'est une excellente occasion de comprendre les techniques locales et d'acheter des souvenirs directement aux créateurs.",
    Avis: "4.6/5 (59)",
    Prix: 135000,
    NombresDeVoyageurs: 4,
    Destinations: "Abomey-Calavi, Sékou",
    DateDeDepart: "2026-07-01",
    GaleriesDImages: [
      "https://www.shutterstock.com/fr/search/abomey-calavi",
      "https://www.youtube.com/watch?v=gT5Fw2Z4c0o",
      "https://www.gettyimages.fr/photos/artisanat-benin",
      "https://www.istockphoto.com/fr/search/2/image?phrase=poterie+benin",
      "https://www.tripadvisor.fr/Attractions-g297920-Activities-c61-t121-Cotonou_Littoral_Department.html"
    ],
    Inclusions: "Rencontre avec des artisans, possibilité d'achat direct, transport.",
  },
  {
    IdVoyage: 20,
    Nom: "Les chutes de Kota (Saison)",
    Description: "Une randonnée vivifiante vers les spectaculaires **chutes de Kota** près de Natitingou (à privilégier en saison des pluies ou juste après). Après une marche à travers une végétation luxuriante, vous atteindrez les cascades, où vous pourrez profiter, si les conditions le permettent, d'une baignade rafraîchissante dans les eaux claires. Le guide assure la sécurité sur le sentier.",
    Avis: "4.5/5 (10)",
    Prix: 190000,
    NombresDeVoyageurs: 5,
    Destinations: "Kota, Natitingou",
    DateDeDepart: "2026-10-10",
    GaleriesDImages: [
      "https://voyageavecnous.com/les-chutes-de-la-kota-natitingou-benin/",
      "https://www.youtube.com/watch?v=Ez1ozpEkkrg",
      "https://www.shutterstock.com/fr/search/chutes+de+kota+benin",
      "https://www.gettyimages.fr/photos/cascades-benin",
      "https://www.istockphoto.com/fr/search/2/image?phrase=natitingou"
    ],
    Inclusions: "Guide de montagne, équipement de sécurité, transport A/R Natitingou.",
  },
];


export default voyagesData